version: "3.8"

services:
  db:
    image: postgres:15
    container_name: movie-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: movie_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    container_name: movie-backend
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://user:pass@db:5432/movie_db
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./movie-player
    container_name: movie-frontend
    ports:
      - "3000:80"

volumes:
  postgres_data: